source "https://rubygems.org"

ruby "3.1.0"
gem "rails", "~> 7.0.3"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "clearance"
gem "pry-rails"
gem "money-rails"
gem "bcrypt"
gem "jwt"
gem "rswag"
gem "rspec-rails"
gem "simplecov"
gem 'rack-cors'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
end
